"""Hand-written T6 — re-shoot framing/camera move. Authored by Claude."""

HAND_T6 = {
"00000_T6_0000": ("Re-shoot shot 2 of the kitchen as an overhead shot, with a slow dolly-in toward the coffee cup.", "an overhead shot"),
"00000_T6_0001": ("Re-shoot shot 3 of the kitchen as an overhead shot, with a smooth tilt-up.", "an overhead shot"),
"00001_T6_0002": ("Re-shoot shot 4 of the meeting as a low-angle medium shot, with a handheld follow.", "a low-angle medium shot"),
"00001_T6_0003": ("Re-shoot shot 2 of the meeting as a low-angle medium shot, with a slow dolly-out.", "a low-angle medium shot"),
"00002_T6_0004": ("Re-shoot shot 3 of the cafe as a dutch-angle medium shot, with a handheld follow.", "a dutch-angle medium shot"),
"00002_T6_0005": ("Re-shoot shot 3 of the cafe as an extreme close-up, with a slow dolly-in.", "an extreme close-up"),
"00003_T6_0006": ("Re-shoot shot 2 of the bedroom as an overhead shot, with a handheld follow.", "an overhead shot"),
"00003_T6_0007": ("Re-shoot shot 2 of the bedroom as an overhead shot, with a left-to-right pan.", "an overhead shot"),
"00004_T6_0008": ("Re-shoot shot 3 of the library as a wide establishing shot, with a handheld follow.", "a wide establishing shot"),
"00004_T6_0009": ("Re-shoot shot 2 of the library as a dutch-angle medium shot, with a left-to-right pan.", "a dutch-angle medium shot"),
"00005_T6_0010": ("Re-shoot shot 5 of the jogging sequence as an extreme close-up, with a slow dolly-in.", "an extreme close-up"),
"00005_T6_0011": ("Re-shoot shot 4 of the jogging sequence as an extreme close-up, with a handheld follow.", "an extreme close-up"),
"00006_T6_0012": ("Re-shoot shot 3 of the kitchen cooking as a wide establishing shot, with a left-to-right pan.", "a wide establishing shot"),
"00006_T6_0013": ("Re-shoot shot 1 of the kitchen cooking as a wide establishing shot, with a handheld follow.", "a wide establishing shot"),
"00007_T6_0014": ("Re-shoot shot 2 of the garage scene as a wide establishing shot, with a handheld follow.", "a wide establishing shot"),
"00007_T6_0015": ("Re-shoot shot 1 of the garage scene as an extreme close-up, with a left-to-right pan.", "an extreme close-up"),
"00008_T6_0016": ("Re-shoot shot 4 of the restaurant scene as an extreme close-up, with a left-to-right pan.", "an extreme close-up"),
"00008_T6_0017": ("Re-shoot shot 3 of the restaurant scene as an extreme close-up, with a handheld follow.", "an extreme close-up"),
"00009_T6_0018": ("Re-shoot shot 2 of the beach walk as a dutch-angle medium shot, with a handheld follow.", "a dutch-angle medium shot"),
"00009_T6_0019": ("Re-shoot shot 3 of the beach walk as an overhead shot, with a slow dolly-in.", "an overhead shot"),
"00010_T6_0020": ("Re-shoot shot 4 of the rooftop scene as a low-angle medium shot, with a handheld follow.", "a low-angle medium shot"),
"00010_T6_0021": ("Re-shoot shot 3 of the rooftop scene as a wide establishing shot, with a slow dolly-out.", "a wide establishing shot"),
"00011_T6_0022": ("Re-shoot shot 1 of the subway scene as a dutch-angle medium shot, with a left-to-right pan.", "a dutch-angle medium shot"),
"00011_T6_0023": ("Re-shoot shot 1 of the subway scene as an extreme close-up, with a slow dolly-out.", "an extreme close-up"),
"00012_T6_0024": ("Re-shoot shot 1 of the forest hike as an extreme close-up, with a handheld follow.", "an extreme close-up"),
"00012_T6_0025": ("Re-shoot shot 4 of the forest hike as a dutch-angle medium shot, with a left-to-right pan.", "a dutch-angle medium shot"),
"00013_T6_0026": ("Re-shoot shot 2 of the bookstore as a wide establishing shot, with a handheld follow.", "a wide establishing shot"),
"00013_T6_0027": ("Re-shoot shot 3 of the bookstore as an overhead shot, with a smooth tilt-up.", "an overhead shot"),
"00014_T6_0028": ("Re-shoot shot 3 of the playground scene as an extreme close-up, with a left-to-right pan.", "an extreme close-up"),
"00014_T6_0029": ("Re-shoot shot 1 of the playground scene as an overhead shot, with a handheld follow.", "an overhead shot"),
"00015_T6_0030": ("Re-shoot shot 3 of the train station farewell as a wide establishing shot, with a slow dolly-out.", "a wide establishing shot"),
"00015_T6_0031": ("Re-shoot shot 3 of the train station farewell as an extreme close-up, with a slow dolly-out.", "an extreme close-up"),
"00016_T6_0032": ("Re-shoot shot 2 of the art studio scene as a low-angle medium shot, with a smooth tilt-up.", "a low-angle medium shot"),
"00016_T6_0033": ("Re-shoot shot 1 of the art studio scene as a wide establishing shot, with a slow dolly-out.", "a wide establishing shot"),
"00017_T6_0034": ("Re-shoot shot 5 of the gym workout as a dutch-angle medium shot, with a handheld follow.", "a dutch-angle medium shot"),
"00017_T6_0035": ("Re-shoot shot 1 of the gym workout as an extreme close-up, with a slow dolly-in.", "an extreme close-up"),
"00018_T6_0036": ("Re-shoot shot 2 of the garden as a dutch-angle medium shot, with a handheld follow.", "a dutch-angle medium shot"),
"00018_T6_0037": ("Re-shoot shot 4 of the garden as an extreme close-up, with a left-to-right pan.", "an extreme close-up"),
"00019_T6_0038": ("Re-shoot shot 1 of the recording studio as a dutch-angle medium shot, with a slow dolly-in.", "a dutch-angle medium shot"),
"00019_T6_0039": ("Re-shoot shot 2 of the recording studio as an extreme close-up, with a smooth tilt-up.", "an extreme close-up"),
"00020_T6_0040": ("Re-shoot shot 1 of the classroom as an extreme close-up, with a handheld follow.", "an extreme close-up"),
"00020_T6_0041": ("Re-shoot shot 1 of the classroom as a low-angle medium shot, with a slow dolly-in.", "a low-angle medium shot"),
"00021_T6_0042": ("Re-shoot shot 1 of the hospital corridor as a low-angle medium shot, with a left-to-right pan.", "a low-angle medium shot"),
"00021_T6_0043": ("Re-shoot shot 2 of the hospital corridor as an extreme close-up, with a handheld follow.", "an extreme close-up"),
"00022_T6_0044": ("Re-shoot shot 1 of the cafe writing scene as a dutch-angle medium shot, with a slow dolly-in.", "a dutch-angle medium shot"),
"00022_T6_0045": ("Re-shoot shot 2 of the cafe writing scene as a wide establishing shot, with a left-to-right pan.", "a wide establishing shot"),
"00023_T6_0046": ("Re-shoot shot 4 of the alley scene as a dutch-angle medium shot, with a slow dolly-out.", "a dutch-angle medium shot"),
"00023_T6_0047": ("Re-shoot shot 2 of the alley scene as an extreme close-up, with a slow dolly-out.", "an extreme close-up"),
"00024_T6_0048": ("Re-shoot shot 3 of the late-night office as a dutch-angle medium shot, with a left-to-right pan.", "a dutch-angle medium shot"),
"00024_T6_0049": ("Re-shoot shot 5 of the late-night office as an overhead shot, with a slow dolly-out.", "an overhead shot"),
"00025_T6_0050": ("Re-shoot shot 4 of the barbershop scene as an overhead shot, with a handheld follow.", "an overhead shot"),
"00025_T6_0051": ("Re-shoot shot 3 of the barbershop scene as a low-angle medium shot, with a smooth tilt-up.", "a low-angle medium shot"),
"00026_T6_0052": ("Re-shoot shot 2 of the rainy street scene as a wide establishing shot, with a handheld follow.", "a wide establishing shot"),
"00026_T6_0053": ("Re-shoot shot 1 of the rainy street scene as an overhead shot, with a slow dolly-in.", "an overhead shot"),
"00027_T6_0054": ("Re-shoot shot 1 of the music lesson as a dutch-angle medium shot, with a left-to-right pan.", "a dutch-angle medium shot"),
"00027_T6_0055": ("Re-shoot shot 2 of the music lesson as an overhead shot, with a left-to-right pan.", "an overhead shot"),
"00028_T6_0056": ("Re-shoot shot 3 of the beach storm scene as a low-angle medium shot, with a handheld follow.", "a low-angle medium shot"),
"00028_T6_0057": ("Re-shoot shot 2 of the beach storm scene as a low-angle medium shot, with a smooth tilt-up.", "a low-angle medium shot"),
"00029_T6_0058": ("Re-shoot shot 4 of the rooftop yoga as an extreme close-up, with a slow dolly-in.", "an extreme close-up"),
"00029_T6_0059": ("Re-shoot shot 2 of the rooftop yoga as a low-angle medium shot, with a slow dolly-out.", "a low-angle medium shot"),
}
