"""Hand-written T4 — object add / remove / replace. Authored by Claude."""

HAND_T4 = {
"00000_T4_0000": ("Place a brass desk bell on the wooden kitchen counter, in every shot the counter is visible.", "a brass desk bell on the kitchen counter"),
"00000_T4_0001": ("Remove the white ceramic coffee cup completely from every shot of the kitchen.", "a kitchen scene without the coffee cup"),
"00001_T4_0002": ("Replace the laptop on the conference table with an old beige CRT monitor, in every shot.", "an old beige CRT monitor"),
"00001_T4_0003": ("Add a small black domestic cat curled up on the glass conference table, in every shot the table is visible.", "a small black cat curled up on the glass table"),
"00002_T4_0004": ("Remove the espresso cup from every shot of the cafe.", "a cafe scene without the espresso cup"),
"00002_T4_0005": ("Place a small black domestic cat curled up on the round metal table, in every shot the table is visible.", "a small black cat curled up on the cafe table"),
"00003_T4_0006": ("Place a small black domestic cat curled up on the white linen bedsheet, in every shot of the bed.", "a small black cat curled up on the bedsheet"),
"00003_T4_0007": ("Replace the smartphone with a vintage rotary dial telephone, wherever it appears in the bedroom.", "a vintage rotary dial telephone"),
"00004_T4_0008": ("Place a fresh bouquet of red roses in a vase on the wooden library desk, in every shot.", "a fresh bouquet of red roses on the desk"),
"00004_T4_0009": ("Replace the open textbook with a rolled-up parchment scroll, in every shot of the library.", "a rolled-up parchment scroll"),
"00005_T4_0010": ("Scatter a small pile of orange autumn leaves along the park path, throughout the jogging sequence.", "orange autumn leaves on the park path"),
"00006_T4_0011": ("Replace the fresh red tomato with a fresh yellow lemon on the cutting board, throughout the cooking scene.", "a fresh yellow lemon on the cutting board"),
"00006_T4_0012": ("Replace the iron skillet on the stove with a copper saucepan, in every shot of the kitchen.", "a copper saucepan on the stove"),
"00007_T4_0013": ("Replace the wrench with a bright orange power drill in the mechanic's hand, throughout the garage scene.", "a bright orange power drill"),
"00008_T4_0014": ("Place a glowing candle in a glass holder on the white tablecloth, in every shot of the restaurant.", "a glowing candle in a glass holder"),
"00008_T4_0015": ("Place a fresh bouquet of red roses in a vase on the white tablecloth, in every shot of the dinner table.", "a fresh bouquet of red roses on the table"),
"00009_T4_0016": ("Scatter a small pile of orange autumn leaves alongside the footprints in the wet sand, throughout the beach walk.", "orange autumn leaves in the wet sand"),
"00009_T4_0017": ("Replace the seashell in her palm with a small white starfish, in every shot of the beach.", "a small white starfish"),
"00010_T4_0018": ("String warm yellow fairy lights along the city skyline, in every shot the skyline is visible.", "a string of warm yellow fairy lights along the skyline"),
"00010_T4_0019": ("Replace the smartphone in his hand with a chunky 1995-style flip phone, in every shot of the rooftop.", "a chunky 1995-style flip phone"),
"00011_T4_0020": ("Replace the paperback book in her hand with a rolled-up parchment scroll, throughout the subway scene.", "a rolled-up parchment scroll"),
"00011_T4_0021": ("Replace the paperback book in her hand with an oversized glossy magazine, throughout the subway scene.", "an oversized magazine with a glossy cover"),
"00012_T4_0022": ("Replace the wooden walking stick with a dried branch covered in autumn leaves, in every shot of the hike.", "a dried branch with autumn leaves"),
"00013_T4_0023": ("String warm yellow fairy lights along the wooden bookshelf, in every shot the shelf is visible.", "a string of warm yellow fairy lights along the bookshelf"),
"00013_T4_0024": ("Replace the hardcover book with the blue spine with a rolled-up parchment scroll, in every shot of the bookstore.", "a rolled-up parchment scroll"),
"00014_T4_0025": ("Scatter a small pile of orange autumn leaves on the playground sand, throughout the playground scene.", "orange autumn leaves on the playground sand"),
"00015_T4_0026": ("Place a small black domestic cat curled up on the train platform near the leather suitcase, in every shot of the platform.", "a small black cat on the train platform"),
"00017_T4_0027": ("Mount a vintage round wall clock on the gym's mirror wall, in every shot of the workout.", "a vintage round wall clock on the gym wall"),
"00017_T4_0028": ("Place a small black domestic cat curled up on the grey gym mat, in every shot the mat is visible.", "a small black cat curled up on the gym mat"),
"00018_T4_0029": ("Scatter a small pile of orange autumn leaves on the rich brown soil, throughout the gardening scene.", "orange autumn leaves on the brown soil"),
"00018_T4_0030": ("Replace the small green plant in the black pot with a tall green succulent in a terracotta pot, in every shot.", "a tall green succulent in a terracotta pot"),
"00019_T4_0031": ("Remove the music sheet stand entirely from every shot of the recording studio.", "a recording studio without the music sheet stand"),
"00019_T4_0032": ("Replace the silver studio microphone with an antique brass microphone on a stand, in every shot.", "an antique brass microphone on a stand"),
"00020_T4_0033": ("Replace the blue marker in the teacher's hand with a quill pen and ink well, throughout the classroom scene.", "a quill pen with an ink well"),
"00020_T4_0034": ("Place a small black domestic cat curled up in front of the whiteboard, in every shot of the classroom.", "a small black cat in front of the whiteboard"),
"00022_T4_0035": ("Replace the ceramic cup of black coffee with a tall iced lemonade in a clear glass, in every shot of the cafe.", "a tall iced lemonade in a clear glass"),
"00022_T4_0036": ("Remove the fountain pen from every shot of the cafe writing scene.", "a cafe scene without the fountain pen"),
"00023_T4_0037": ("String warm yellow fairy lights along the brick alley wall, in every shot the wall is visible.", "a string of warm yellow fairy lights along the alley wall"),
"00023_T4_0038": ("Mount a small framed family photograph on the brick alley wall, in every shot of the alley.", "a small framed family photograph on the alley wall"),
"00024_T4_0039": ("Remove all the scattered papers from the desk, in every shot of the late-night office.", "a desk without scattered papers"),
"00024_T4_0040": ("Replace the empty white coffee mug with a tall iced lemonade in a clear glass, throughout the office scene.", "a tall iced lemonade in a clear glass"),
"00025_T4_0041": ("Mount a small framed family photograph on the large barbershop mirror, in every shot of the mirror.", "a small framed family photograph on the mirror"),
"00025_T4_0042": ("Mount a vintage round wall clock above the large barbershop mirror, in every shot of the haircut.", "a vintage round wall clock above the mirror"),
"00026_T4_0043": ("Remove the red umbrella entirely from every shot of the rainy street scene.", "a rainy street scene without the red umbrella"),
"00026_T4_0044": ("Replace the red umbrella with a yellow flower-patterned parasol, in every shot of the rainy street.", "a yellow flower-patterned parasol"),
"00027_T4_0045": ("Remove the sheet music entirely from every shot of the music lesson.", "a music lesson scene without the sheet music"),
"00027_T4_0046": ("Replace the sheet music on the stand with a rolled-up parchment scroll, in every shot of the lesson.", "a rolled-up parchment scroll"),
"00028_T4_0047": ("Replace the wooden stick on the stormy beach with a dried branch covered in autumn leaves, in every shot.", "a dried branch with autumn leaves"),
"00029_T4_0048": ("Place a small black domestic cat curled up on the purple yoga mat, in every shot of the rooftop yoga.", "a small black cat curled up on the yoga mat"),
"00029_T4_0049": ("String warm yellow fairy lights across the city sunrise skyline, in every shot the skyline is visible.", "a string of warm yellow fairy lights across the skyline"),
}
