"""Historical v1/v1.2 hand-written T3 — global style/lighting.

Current v2_10s production T3 is style-only; lighting moved to T7. The current
source of truth is `runs/edit_prompts_v2_10s/T3.json` plus `tasks.py`/`banks.py`.

For each (scene, style) pair I picked phrasing that anchors the style to
something specific in the scene (kitchen, library, beach, etc.) so the
editor has more to lock onto than a bare style adjective.
"""

HAND_T3 = {
"00000_T3_0000": ("Re-render the entire kitchen scene as a midday neon-lit cyberpunk street: keep the action, but every surface is bathed in saturated neon and chrome.", "a midday neon-lit cyberpunk look"),
"00000_T3_0001": ("Render the whole video as an infrared thermal-camera view; warm bodies glow bright, cold surfaces stay dark.", "an infrared thermal-camera look"),
"00001_T3_0002": ("Re-light the entire meeting as a cold, blue moonlit night scene; the conference room becomes lit only by moonlight through the glass walls.", "a cold blue moonlit night look"),
"00001_T3_0003": ("Bathe the entire meeting in warm golden-hour sunset light, throughout every shot.", "a warm golden-hour sunset look"),
"00002_T3_0004": ("Bathe the cafe scene in warm golden-hour sunset light from start to finish, keeping the action unchanged.", "a warm golden-hour sunset look"),
"00002_T3_0005": ("Re-render the cafe scene with underwater lighting and caustic ripples drifting across every surface.", "an underwater lighting with caustic ripples look"),
"00003_T3_0006": ("Re-light the bedroom scene as a cold blue moonlit night, throughout every shot.", "a cold blue moonlit night look"),
"00003_T3_0007": ("Render the entire bedroom scene as anime cel-shaded animation with bold black outlines.", "an anime cel-shaded look with bold black outlines"),
"00004_T3_0008": ("Re-render the library scene as stop-motion clay animation, every shot included.", "a stop-motion clay animation look"),
"00004_T3_0009": ("Render the library scene as film-noir black-and-white with deep shadows and high contrast.", "a film noir black-and-white look with deep shadows"),
"00005_T3_0010": ("Render the jogging sequence as an infrared thermal-camera view; the runner glows bright against a cold dark background.", "an infrared thermal-camera look"),
"00005_T3_0011": ("Re-render the jogging sequence as anime cel-shaded animation with bold black outlines, throughout the video.", "an anime cel-shaded look with bold black outlines"),
"00006_T3_0012": ("Re-render the cooking scene as stop-motion clay animation, throughout every shot.", "a stop-motion clay animation look"),
"00006_T3_0013": ("Re-light the kitchen with underwater lighting and caustic ripples drifting across every surface.", "an underwater lighting with caustic ripples look"),
"00007_T3_0014": ("Re-render the garage scene as stop-motion clay animation, throughout the video.", "a stop-motion clay animation look"),
"00007_T3_0015": ("Bathe the garage scene in underwater lighting with caustic ripples drifting across every surface.", "an underwater lighting with caustic ripples look"),
"00008_T3_0016": ("Render the entire restaurant scene as an infrared thermal-camera view; warm bodies and food glow bright against the cool dining room.", "an infrared thermal-camera look"),
"00008_T3_0017": ("Re-render the restaurant scene as an oil painting with visible brush strokes throughout.", "an oil painting look with visible brush strokes"),
"00009_T3_0018": ("Bathe the entire beach walk in warm golden-hour sunset light, throughout every shot.", "a warm golden-hour sunset look"),
"00009_T3_0019": ("Re-light the beach walk as a cold, blue moonlit night scene; the orange sky becomes silver and dark.", "a cold blue moonlit night look"),
"00010_T3_0020": ("Render the rooftop scene as a cold, blue moonlit night, throughout every shot.", "a cold blue moonlit night look"),
"00010_T3_0021": ("Re-render the entire rooftop sequence as 1990s VHS camcorder footage with chromatic noise and tracking lines.", "a 1990s VHS camcorder footage look with chromatic noise"),
"00011_T3_0022": ("Re-render the subway scene as a midday neon-lit cyberpunk street: saturated neon, reflective surfaces, vibrant signage.", "a midday neon-lit cyberpunk look"),
"00011_T3_0023": ("Render the entire subway sequence as 1990s VHS camcorder footage with chromatic noise and faint tracking lines.", "a 1990s VHS camcorder footage look with chromatic noise"),
"00012_T3_0024": ("Re-light the forest hike with underwater lighting and caustic ripples shimmering through the trees.", "an underwater lighting with caustic ripples look"),
"00012_T3_0025": ("Re-render the forest hike as an oil painting with visible brush strokes, throughout every shot.", "an oil painting look with visible brush strokes"),
"00013_T3_0026": ("Re-render the bookstore scene as stop-motion clay animation, throughout every shot.", "a stop-motion clay animation look"),
"00013_T3_0027": ("Re-render the bookstore scene as an oil painting with visible brush strokes, throughout the video.", "an oil painting look with visible brush strokes"),
"00014_T3_0028": ("Render the playground scene as an oil painting with visible brush strokes, throughout the video.", "an oil painting look with visible brush strokes"),
"00014_T3_0029": ("Render the playground scene as anime cel-shaded animation with bold black outlines, every shot.", "an anime cel-shaded look with bold black outlines"),
"00015_T3_0030": ("Re-render the train station farewell as stop-motion clay animation, throughout the video.", "a stop-motion clay animation look"),
"00015_T3_0031": ("Render the entire train station scene as an infrared thermal-camera view, throughout every shot.", "an infrared thermal-camera look"),
"00016_T3_0032": ("Bathe the art studio in warm golden-hour sunset light, throughout every shot.", "a warm golden-hour sunset look"),
"00016_T3_0033": ("Re-render the art studio scene as stop-motion clay animation, throughout the video.", "a stop-motion clay animation look"),
"00017_T3_0034": ("Render the gym scene as film-noir black-and-white with deep shadows and harsh key light.", "a film noir black-and-white look with deep shadows"),
"00017_T3_0035": ("Re-render the gym scene as stop-motion clay animation, throughout every shot.", "a stop-motion clay animation look"),
"00018_T3_0036": ("Re-light the garden as a cold, blue moonlit night, throughout every shot.", "a cold blue moonlit night look"),
"00018_T3_0037": ("Re-render the garden scene as an oil painting with visible brush strokes throughout.", "an oil painting look with visible brush strokes"),
"00019_T3_0038": ("Render the recording studio scene as an infrared thermal-camera view, throughout the video.", "an infrared thermal-camera look"),
"00019_T3_0039": ("Re-render the recording studio scene as film-noir black-and-white with deep shadows.", "a film noir black-and-white look with deep shadows"),
"00020_T3_0040": ("Render the classroom scene as an infrared thermal-camera view; warm students glow against the cool board and walls.", "an infrared thermal-camera look"),
"00020_T3_0041": ("Re-render the classroom scene as a midday neon-lit cyberpunk street with saturated neon signage and chrome surfaces.", "a midday neon-lit cyberpunk look"),
"00021_T3_0042": ("Re-render the hospital corridor scene as an oil painting with visible brush strokes throughout.", "an oil painting look with visible brush strokes"),
"00021_T3_0043": ("Render the hospital corridor as film-noir black-and-white with deep shadows and dramatic high contrast.", "a film noir black-and-white look with deep shadows"),
"00022_T3_0044": ("Re-render the cafe writing scene as anime cel-shaded animation with bold black outlines.", "an anime cel-shaded look with bold black outlines"),
"00022_T3_0045": ("Render the entire cafe writing scene as 1990s VHS camcorder footage with chromatic noise and tracking lines.", "a 1990s VHS camcorder footage look with chromatic noise"),
"00023_T3_0046": ("Render the alley cat scene as film-noir black-and-white with deep shadows and dramatic key light.", "a film noir black-and-white look with deep shadows"),
"00023_T3_0047": ("Bathe the alley cat scene in warm golden-hour sunset light, throughout every shot.", "a warm golden-hour sunset look"),
"00024_T3_0048": ("Re-render the late-night office as anime cel-shaded animation with bold black outlines.", "an anime cel-shaded look with bold black outlines"),
"00024_T3_0049": ("Render the late-night office as an infrared thermal-camera view; the woman glows warm against the cold dark room.", "an infrared thermal-camera look"),
"00025_T3_0050": ("Re-light the barbershop as a cold, blue moonlit night, throughout every shot.", "a cold blue moonlit night look"),
"00025_T3_0051": ("Re-render the barbershop scene as a midday neon-lit cyberpunk street with saturated neon and chrome.", "a midday neon-lit cyberpunk look"),
"00026_T3_0052": ("Render the rainy street scene as film-noir black-and-white with deep shadows and high contrast.", "a film noir black-and-white look with deep shadows"),
"00026_T3_0053": ("Re-light the rainy street as a cold, blue moonlit night; even the neon signs read as cold blue.", "a cold blue moonlit night look"),
"00027_T3_0054": ("Render the entire piano lesson as an infrared thermal-camera view, throughout every shot.", "an infrared thermal-camera look"),
"00027_T3_0055": ("Re-render the piano lesson as a midday neon-lit cyberpunk street: the wooden upright piano glows under saturated neon signage.", "a midday neon-lit cyberpunk look"),
"00028_T3_0056": ("Bathe the stormy beach scene in warm golden-hour sunset light, replacing the storm clouds with warm orange skies.", "a warm golden-hour sunset look"),
"00028_T3_0057": ("Render the entire beach storm scene as an infrared thermal-camera view, throughout every shot.", "an infrared thermal-camera look"),
"00029_T3_0058": ("Re-light the rooftop yoga with underwater lighting and caustic ripples drifting across every surface.", "an underwater lighting with caustic ripples look"),
"00029_T3_0059": ("Re-render the rooftop yoga scene as stop-motion clay animation, throughout every shot.", "a stop-motion clay animation look"),
}
