"""Historical v1/v1.2 hand-written T7 — transition style.

Current v2_10s production T7 is global lighting, defined in
`runs/edit_prompts_v2_10s/T7.json`, `tasks.py`, and `banks.py`. This module is
kept only for regenerating the old v1.2 prompt snapshot.

Avoids the v1 bug "use iris-outs" (plural noun on a transition name) and the
'a' vs 'an' issue.
"""

HAND_T7 = {
"00000_T7_0000": ("Replace every hard cut between shots in the kitchen scene with an iris-out transition.", "an iris-out transition"),
"00000_T7_0001": ("Connect the shots of the kitchen scene with match-cuts on motion instead of hard cuts.", "a match-cut on motion transition"),
"00001_T7_0002": ("Replace every hard cut in the meeting with a smooth crossfade.", "a smooth crossfade transition"),
"00001_T7_0003": ("Replace every hard cut in the meeting with a white flash transition.", "a white flash transition"),
"00002_T7_0004": ("Connect the shots of the cafe scene with rotational wipes instead of hard cuts.", "a rotational wipe transition"),
"00002_T7_0005": ("Replace every hard cut in the cafe scene with an iris-out transition.", "an iris-out transition"),
"00003_T7_0006": ("Replace every hard cut in the bedroom scene with an iris-out transition.", "an iris-out transition"),
"00003_T7_0007": ("Replace every hard cut in the bedroom scene with a white flash transition.", "a white flash transition"),
"00004_T7_0008": ("Connect the shots of the library scene with iris-outs instead of hard cuts.", "an iris-out transition"),
"00004_T7_0009": ("Replace every hard cut in the library scene with a white flash transition.", "a white flash transition"),
"00005_T7_0010": ("Connect the shots of the jogging sequence with rotational wipes instead of hard cuts.", "a rotational wipe transition"),
"00005_T7_0011": ("Replace every hard cut in the jogging sequence with a slow cross-dissolve.", "a slow cross-dissolve transition"),
"00006_T7_0012": ("Connect the shots of the cooking scene with rotational wipes instead of hard cuts.", "a rotational wipe transition"),
"00006_T7_0013": ("Replace every hard cut in the cooking scene with a slow cross-dissolve.", "a slow cross-dissolve transition"),
"00007_T7_0014": ("Replace every hard cut in the garage scene with a white flash transition.", "a white flash transition"),
"00007_T7_0015": ("Connect the shots of the garage scene with slow cross-dissolves instead of hard cuts.", "a slow cross-dissolve transition"),
"00008_T7_0016": ("Replace every hard cut in the restaurant scene with a smooth crossfade.", "a smooth crossfade transition"),
"00008_T7_0017": ("Connect the shots of the restaurant scene with rotational wipes instead of hard cuts.", "a rotational wipe transition"),
"00009_T7_0018": ("Replace every hard cut on the beach walk with a white flash transition.", "a white flash transition"),
"00009_T7_0019": ("Connect the shots of the beach walk with rotational wipes instead of hard cuts.", "a rotational wipe transition"),
"00010_T7_0020": ("Connect the rooftop phone-call shots with match-cuts on motion instead of hard cuts.", "a match-cut on motion transition"),
"00010_T7_0021": ("Replace every hard cut in the rooftop scene with a rotational wipe.", "a rotational wipe transition"),
"00011_T7_0022": ("Replace every hard cut in the subway scene with a slow cross-dissolve.", "a slow cross-dissolve transition"),
"00011_T7_0023": ("Replace every hard cut in the subway scene with a white flash transition.", "a white flash transition"),
"00012_T7_0024": ("Replace every hard cut on the forest hike with a smooth crossfade.", "a smooth crossfade transition"),
"00012_T7_0025": ("Connect the forest-hike shots with match-cuts on motion instead of hard cuts.", "a match-cut on motion transition"),
"00013_T7_0026": ("Connect the bookstore shots with match-cuts on motion instead of hard cuts.", "a match-cut on motion transition"),
"00013_T7_0027": ("Replace every hard cut in the bookstore scene with a white flash transition.", "a white flash transition"),
"00014_T7_0028": ("Replace every hard cut in the playground scene with an iris-out transition.", "an iris-out transition"),
"00014_T7_0029": ("Connect the playground shots with rotational wipes instead of hard cuts.", "a rotational wipe transition"),
"00015_T7_0030": ("Replace every hard cut in the train station farewell with a smooth crossfade.", "a smooth crossfade transition"),
"00015_T7_0031": ("Replace every hard cut in the train station farewell with a white flash transition.", "a white flash transition"),
"00016_T7_0032": ("Replace every hard cut in the art studio scene with an iris-out transition.", "an iris-out transition"),
"00016_T7_0033": ("Replace every hard cut in the art studio scene with a white flash transition.", "a white flash transition"),
"00017_T7_0034": ("Connect the gym workout shots with rotational wipes instead of hard cuts.", "a rotational wipe transition"),
"00017_T7_0035": ("Replace every hard cut in the gym workout with a slow cross-dissolve.", "a slow cross-dissolve transition"),
"00018_T7_0036": ("Connect the garden shots with rotational wipes instead of hard cuts.", "a rotational wipe transition"),
"00018_T7_0037": ("Replace every hard cut in the garden scene with an iris-out transition.", "an iris-out transition"),
"00019_T7_0038": ("Replace every hard cut in the recording session with an iris-out transition.", "an iris-out transition"),
"00019_T7_0039": ("Connect the recording-session shots with rotational wipes instead of hard cuts.", "a rotational wipe transition"),
"00020_T7_0040": ("Replace every hard cut in the classroom scene with a white flash transition.", "a white flash transition"),
"00020_T7_0041": ("Replace every hard cut in the classroom scene with a smooth crossfade.", "a smooth crossfade transition"),
"00021_T7_0042": ("Connect the hospital-corridor shots with rotational wipes instead of hard cuts.", "a rotational wipe transition"),
"00021_T7_0043": ("Replace every hard cut in the hospital corridor scene with a smooth crossfade.", "a smooth crossfade transition"),
"00022_T7_0044": ("Replace every hard cut in the cafe writing scene with a smooth crossfade.", "a smooth crossfade transition"),
"00022_T7_0045": ("Replace every hard cut in the cafe writing scene with an iris-out transition.", "an iris-out transition"),
"00023_T7_0046": ("Connect the alley-scene shots with match-cuts on motion instead of hard cuts.", "a match-cut on motion transition"),
"00023_T7_0047": ("Replace every hard cut in the alley scene with a smooth crossfade.", "a smooth crossfade transition"),
"00024_T7_0048": ("Connect the late-night office shots with rotational wipes instead of hard cuts.", "a rotational wipe transition"),
"00024_T7_0049": ("Replace every hard cut in the late-night office scene with an iris-out transition.", "an iris-out transition"),
"00025_T7_0050": ("Replace every hard cut in the barbershop scene with a white flash transition.", "a white flash transition"),
"00025_T7_0051": ("Replace every hard cut in the barbershop scene with a slow cross-dissolve.", "a slow cross-dissolve transition"),
"00026_T7_0052": ("Connect the rainy-street shots with match-cuts on motion instead of hard cuts.", "a match-cut on motion transition"),
"00026_T7_0053": ("Replace every hard cut in the rainy street scene with a white flash transition.", "a white flash transition"),
"00027_T7_0054": ("Connect the music lesson shots with match-cuts on motion instead of hard cuts.", "a match-cut on motion transition"),
"00027_T7_0055": ("Replace every hard cut in the music lesson with a smooth crossfade.", "a smooth crossfade transition"),
"00028_T7_0056": ("Replace every hard cut in the stormy beach scene with a slow cross-dissolve.", "a slow cross-dissolve transition"),
"00028_T7_0057": ("Connect the stormy-beach shots with rotational wipes instead of hard cuts.", "a rotational wipe transition"),
"00029_T7_0058": ("Replace every hard cut in the rooftop yoga scene with a slow cross-dissolve.", "a slow cross-dissolve transition"),
"00029_T7_0059": ("Connect the rooftop yoga shots with match-cuts on motion instead of hard cuts.", "a match-cut on motion transition"),
}
