"""Historical v1/v1.2 hand-written T2 — attribute change.

Current v2_10s production T2 is defined in
`runs/edit_prompts_v2_10s/T2.json`, `tasks.py`, and `banks.py`. This module is
kept only for regenerating the old v1.2 prompt snapshot, whose attribute scope
included accessory and clothing-type changes.
"""

HAND_T2 = {
"00000_T2_0000": ("Add round gold-rimmed glasses to the young woman in the red knit sweater, in every shot of the kitchen.", "a person wearing round gold-rimmed glasses"),
"00000_T2_0001": ("Place a wide-brimmed straw hat on the young woman in the red knit sweater, throughout the video.", "a person wearing a wide-brimmed straw hat"),
"00000_T2_0002": ("In every shot, give the older man in the navy blue shirt mirrored aviator sunglasses.", "a person wearing mirrored aviator sunglasses"),
"00000_T2_0003": ("Change the older man's navy blue shirt to a tie-dye shirt, throughout the kitchen scene.", "a person wearing a tie-dye shirt"),
"00001_T2_0004": ("Change the hair colour of the man in the grey suit jacket to platinum white, in every shot.", "a person with platinum white hair"),
"00001_T2_0005": ("Replace the man's grey suit jacket with a pure white shirt, throughout the meeting.", "a person wearing a pure white shirt"),
"00001_T2_0006": ("Re-dress the woman in her white blouse as still pure white but with a fresh, cleaner cut, in every shot.", "a person wearing a pure white shirt"),
"00001_T2_0007": ("Add thick black-rimmed glasses to the blonde woman in the white blouse, throughout the meeting.", "a person wearing thick black-rimmed glasses"),
"00002_T2_0008": ("Swap the woman's black leather jacket for an electric blue jacket, throughout the cafe scene.", "a person wearing an electric blue jacket"),
"00002_T2_0009": ("Place mirrored aviator sunglasses on the woman with the curly red hair, in every shot.", "a person wearing mirrored aviator sunglasses"),
"00002_T2_0010": ("Add mirrored aviator sunglasses to the bearded man in the beige cardigan, throughout the cafe scene.", "a person wearing mirrored aviator sunglasses"),
"00002_T2_0011": ("Change the bearded man's hair to platinum white, in every shot of the cafe.", "a person with platinum white hair"),
"00003_T2_0012": ("Recolour the young man's messy dark hair to platinum white, throughout the bedroom scene.", "a person with platinum white hair"),
"00003_T2_0013": ("Re-dress the young man in a black leather jacket instead of his white t-shirt, in every shot.", "a person wearing a black leather jacket"),
"00004_T2_0014": ("Change the girl's dark hair to neon green, throughout the library scene.", "a person with neon green hair"),
"00004_T2_0015": ("Replace the girl's green hoodie with a pure white shirt, in every shot.", "a person wearing a pure white shirt"),
"00005_T2_0016": ("Recolour the athletic woman's short black hair to platinum white, throughout the jogging sequence.", "a person with platinum white hair"),
"00005_T2_0017": ("Swap the athletic woman's blue running jacket for a tie-dye shirt, in every shot.", "a person wearing a tie-dye shirt"),
"00006_T2_0018": ("Place a wide-brimmed straw hat on the bearded man in the navy apron, throughout the kitchen.", "a person wearing a wide-brimmed straw hat"),
"00006_T2_0019": ("Re-dress the bearded chef in a bright yellow jacket instead of his navy apron, in every shot.", "a person wearing a bright yellow jacket"),
"00007_T2_0020": ("Replace the mechanic's blue overalls with a tie-dye shirt, throughout the garage scene.", "a person wearing a tie-dye shirt"),
"00007_T2_0021": ("Add round gold-rimmed glasses to the mechanic with the brown braids, in every shot of the garage.", "a person wearing round gold-rimmed glasses"),
"00008_T2_0022": ("Change the slim waiter's hair colour to deep red, throughout the restaurant scene.", "a person with deep red hair"),
"00008_T2_0023": ("Place mirrored aviator sunglasses on the waiter in the black vest, in every shot.", "a person wearing mirrored aviator sunglasses"),
"00008_T2_0024": ("Replace the elderly woman's purple shawl with a striped black-and-white shirt, throughout the dinner scene.", "a person wearing a striped black-and-white shirt"),
"00008_T2_0025": ("Add thick black-rimmed glasses to the elderly woman in the purple shawl, in every shot.", "a person wearing thick black-rimmed glasses"),
"00009_T2_0026": ("Place a red baseball cap on the young woman in the yellow summer dress, throughout the beach walk.", "a person wearing a red baseball cap"),
"00009_T2_0027": ("Replace the young woman's yellow dress with a pure white shirt, in every shot of the beach.", "a person wearing a pure white shirt"),
"00009_T2_0028": ("Re-dress the young man on the beach in a bright yellow jacket instead of his white linen shirt, throughout the walk.", "a person wearing a bright yellow jacket"),
"00009_T2_0029": ("Change the young man's white linen shirt to a tie-dye shirt, in every shot of the beach.", "a person wearing a tie-dye shirt"),
"00010_T2_0030": ("Swap the man's charcoal grey overcoat for a black leather jacket, throughout the rooftop phone call.", "a person wearing a black leather jacket"),
"00010_T2_0031": ("Recolour the man's short dark hair to bright pink, in every shot on the rooftop.", "a person with bright pink hair"),
"00011_T2_0032": ("Place a wide-brimmed straw hat on the woman in the tan trench coat, throughout the subway scene.", "a person wearing a wide-brimmed straw hat"),
"00011_T2_0033": ("Change the woman's brown bob to bright pink hair, in every shot of the subway.", "a person with bright pink hair"),
"00012_T2_0034": ("Recolour the hiker's hair to platinum white, throughout the forest hike.", "a person with platinum white hair"),
"00012_T2_0035": ("Add a bright yellow jacket on the hiker (instead of his current top), in every shot of the trail.", "a person wearing a bright yellow jacket"),
"00013_T2_0036": ("Recolour the woman's short pink hair to a more saturated bright pink, throughout the bookstore scene.", "a person with bright pink hair"),
"00013_T2_0037": ("Swap the woman's round glasses for round gold-rimmed glasses, in every shot.", "a person wearing round gold-rimmed glasses"),
"00013_T2_0038": ("Replace the man's maroon sweater with a striped black-and-white shirt, throughout the bookstore scene.", "a person wearing a striped black-and-white shirt"),
"00013_T2_0039": ("Place a knit beanie on the man in the maroon sweater, in every shot of the bookstore.", "a person wearing a knit beanie"),
"00014_T2_0040": ("Place a knit beanie on the small girl in the pink jacket, throughout the playground scene.", "a person wearing a knit beanie"),
"00014_T2_0041": ("Change the girl's ginger hair to deep red, in every shot of the playground.", "a person with deep red hair"),
"00015_T2_0042": ("Add mirrored aviator sunglasses to the older woman in the long green coat, throughout the train station scene.", "a person wearing mirrored aviator sunglasses"),
"00015_T2_0043": ("Swap the older woman's long green coat for a black leather jacket, in every shot of the platform.", "a person wearing a black leather jacket"),
"00015_T2_0044": ("Replace the man's dark wool coat with a tie-dye shirt, throughout the farewell scene.", "a person wearing a tie-dye shirt"),
"00015_T2_0045": ("Place a red baseball cap on the man in the dark wool coat, in every shot.", "a person wearing a red baseball cap"),
"00016_T2_0046": ("Add mirrored aviator sunglasses to the elderly painter in the paint-stained apron, throughout the studio scene.", "a person wearing mirrored aviator sunglasses"),
"00016_T2_0047": ("Replace the painter's grey apron with a pure white shirt, in every shot of the studio.", "a person wearing a pure white shirt"),
"00017_T2_0048": ("Place a wide-brimmed straw hat on the muscular man in the gym, throughout the workout.", "a person wearing a wide-brimmed straw hat"),
"00017_T2_0049": ("Give the muscular man bright pink hair (instead of his shaved head), in every shot of the gym.", "a person with bright pink hair"),
"00018_T2_0050": ("Re-dress the older gardener in an electric blue jacket instead of his brown vest, throughout the garden.", "a person wearing an electric blue jacket"),
"00018_T2_0051": ("Add thick black-rimmed glasses to the older man in the straw hat, in every shot of the garden.", "a person wearing thick black-rimmed glasses"),
"00019_T2_0052": ("Replace the young woman's denim shirt with a pure white shirt, throughout the recording studio scene.", "a person wearing a pure white shirt"),
"00019_T2_0053": ("Add round gold-rimmed glasses to the young woman with the purple hair, in every shot.", "a person wearing round gold-rimmed glasses"),
"00020_T2_0054": ("Replace the teacher's cream blouse with a bright yellow jacket, throughout the classroom scene.", "a person wearing a bright yellow jacket"),
"00020_T2_0055": ("Re-dress the teacher in a pure white shirt instead of her cream blouse, in every shot.", "a person wearing a pure white shirt"),
"00021_T2_0056": ("Place a red baseball cap on the female doctor in the white coat, throughout the corridor scene.", "a person wearing a red baseball cap"),
"00021_T2_0057": ("Add mirrored aviator sunglasses to the female doctor, in every shot of the hospital corridor.", "a person wearing mirrored aviator sunglasses"),
"00021_T2_0058": ("Recolour the patient's brown hair to neon green, throughout the corridor scene.", "a person with neon green hair"),
"00021_T2_0059": ("Swap the patient's beige cardigan for a black leather jacket, in every shot.", "a person wearing a black leather jacket"),
"00022_T2_0060": ("Place a knit beanie on the man in the green sweater, throughout the cafe writing scene.", "a person wearing a knit beanie"),
"00022_T2_0061": ("Swap the man's round wire glasses for thick black-rimmed glasses, in every shot of the cafe.", "a person wearing thick black-rimmed glasses"),
"00023_T2_0062": ("Add thick black-rimmed glasses to the young man in the grey hoodie, throughout the alley scene.", "a person wearing thick black-rimmed glasses"),
"00023_T2_0063": ("Recolour the young man's blond hair to bright pink, in every shot of the alley.", "a person with bright pink hair"),
"00024_T2_0064": ("Add thick black-rimmed glasses to the tired woman in the white shirt, throughout the late-night office scene.", "a person wearing thick black-rimmed glasses"),
"00024_T2_0065": ("Place a red baseball cap on the tired woman, in every shot of the office.", "a person wearing a red baseball cap"),
"00025_T2_0066": ("Place a red baseball cap on the barber with the handlebar mustache, throughout the haircut.", "a person wearing a red baseball cap"),
"00025_T2_0067": ("Recolour the barber's hair to platinum white, in every shot of the barbershop.", "a person with platinum white hair"),
"00025_T2_0068": ("Re-dress the young customer in an electric blue jacket instead of his grey t-shirt, throughout the haircut.", "a person wearing an electric blue jacket"),
"00025_T2_0069": ("Recolour the young customer's shaggy brown hair to bright pink, in every shot.", "a person with bright pink hair"),
"00026_T2_0070": ("Add thick black-rimmed glasses to the woman in the long black raincoat, throughout the rainy street scene.", "a person wearing thick black-rimmed glasses"),
"00026_T2_0071": ("Recolour the woman's chin-length black hair to deep red, in every shot.", "a person with deep red hair"),
"00027_T2_0072": ("Replace the older man's brown tweed vest with a tie-dye shirt, throughout the music lesson.", "a person wearing a tie-dye shirt"),
"00027_T2_0073": ("Recolour the older man's bushy white hair to deep red, in every shot of the lesson.", "a person with deep red hair"),
"00027_T2_0074": ("Place a knit beanie on the small girl in the pale yellow dress, throughout the music lesson.", "a person wearing a knit beanie"),
"00027_T2_0075": ("Recolour the small girl's black braids to neon green, in every shot.", "a person with neon green hair"),
"00028_T2_0076": ("Place a red baseball cap on the man in the red windbreaker, throughout the stormy beach scene.", "a person wearing a red baseball cap"),
"00028_T2_0077": ("Swap the man's red windbreaker for an electric blue jacket, in every shot.", "a person wearing an electric blue jacket"),
"00028_T2_0078": ("Dress the golden retriever in a small electric blue dog jacket, throughout the beach scene.", "a dog wearing an electric blue jacket"),
"00028_T2_0079": ("Dress the golden retriever in a small pure white shirt, in every shot of the beach.", "a dog wearing a pure white shirt"),
"00029_T2_0080": ("Place a red baseball cap on the woman in the grey yoga clothes, throughout the rooftop yoga scene.", "a person wearing a red baseball cap"),
"00029_T2_0081": ("Recolour the woman's auburn hair to platinum white, in every shot of the rooftop.", "a person with platinum white hair"),
}
